install.packages("ggplot2")
install.packages("tidyr")
install.packages("dplyr")
install.packages("vegan")
install.packages("pheatmap")
install.packages("highr")
install.packages("markdown")
install.packages("yaml")
install.packages("caTools")
install.packages("knitr")
install.packages("rprojroot")
install.packages("rmarkdown")
source("https://bioconductor.org/biocLite.R")
BiocInstaller::biocLite(c("GenomicAlignments", "VariantAnnotation", "Biostrings", "GenomicFeatures"))
